<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--CSS -->
    <link href="{{asset('res/css/all.min.css')}}" rel="stylesheet" >
    <link href="{{asset('res/css/bootstrap.min.css')}}" rel="stylesheet" >
    <link href="{{asset('res/css/my jobs.css')}}" rel="stylesheet" >
    <link rel="stylesheet" href="{{asset('res/css/viwe-prof.css')}}">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{asset('res/images/Logo.svg')}}" type="image/x-icon" />

    <title>my jobs</title>
  </head>
  <body>
    <header class="h">
      <div class="h1">
        <img class="Logo" src="{{asset('res/images/Logo.svg')}}" alt="Logo">
        <a id="h1-a" href="/Users/AL-FAJR/Desktop/Project/gal1/index.html">Gallery</a>
        <a id="main" href="">Find Work</a>
        <a id="h1-a" href="">Forum</a>
        <a id="h1-a" href="">Store</a>
      </div>


      <div class="h2">
        <a id="h2-a" href=""><img src="{{asset('res/images/mes.svg')}}" height="10px" width="auto"></a>
        <a id="h2-a" href=""><img src="{{asset('res/images/not.svg')}}" height="25px" width="auto"></a>
        <button class="content-button" onclick="viewbutton();"><a id="h2-a1"><img id="profile" src="{{asset('res/images/profile.png')}}" height="45px" width="45px"></a>
        </button>

        <div id="file-div" class="contents-items">
          <ul class="items-list">
              <li><a href="Profile – 1.html">Profile</a></li>
              <li>Account</li>
              <li>Setting</li>
              <li>Log Out</li>
          </ul>
      </div>

      </div>

    </header>
    <main>
      <div id="navi">
        <a id="a" href="Homepage (Freelancing) .html">Search for jobs</a>
        <a id="a" href="my Proposal.html">my Proposal</a>
        <a id="select-nav" href="#">my jobs</a>
        <a id="a" href="Reports (Empty).html">Reports</a>
        <a id="a" href="Message.html">Message</a>
      </div>
      <div id="jop-option" >
        <a id="jop-a" href="#">Working Jobs</a>
        <a id="jop-a1" href="Completed jobs.html">Completed jobs</a>
      </div>

      <div id="componnt">
        <div id="jop">
            <a href="my jop detal.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>


            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
          </div>
          <div id="jop">
            <a href="" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>


            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
          </div>
          <div id="jop">
            <a href="" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>


            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
            </div>
          <div id="jop">
            <a href="" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id=" feltar-option">
              <img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>
              <img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>
              <img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span>
              <img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span>
              <img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label>
              <img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label>
            </div>

            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
          </div>

          <div id="jop">
            <a href="" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>


            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
          </div>
          <div id="jop">
            <a href="" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>

            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
          </div>
          <div id="jop">
            <a href="" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>

            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
          </div>
          <div id="see-more">
            <div id="jop">
                <a href="Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
                <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
                <div id="feltar-option">
                  <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                  <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                  <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                  <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
                </div>

                <br>
                  <b id="descrb" >
                    This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                  </b>
                <br>
                  <div id="catogr">
                    <span id="type-catogr">Analytics and creative thinking</span>
                    <span id="type-catogr">Garden Design</span>
                    <span id="type-catogr">render</span>
                  </div>
              </div>
              <div id="jop">
                <a href="Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
                <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
                <div id="feltar-option">
                  <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                  <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                  <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                  <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
                </div>

                <br>
                  <b id="descrb" >
                    This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                  </b>
                <br>
                  <div id="catogr">
                    <span id="type-catogr">Analytics and creative thinking</span>
                    <span id="type-catogr">Garden Design</span>
                    <span id="type-catogr">render</span>
                  </div>
                </div>
              <div id="jop">
                <a href="Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
                <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
                <div id="feltar-option">
                  <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                  <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                  <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                  <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
                </div>

                <br>
                  <b id="descrb" >
                    This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                  </b>
                <br>
                  <div id="catogr">
                    <span id="type-catogr">Analytics and creative thinking</span>
                    <span id="type-catogr">Garden Design</span>
                    <span id="type-catogr">render</span>
                  </div>
              </div>

              <div id="jop">
                <a href="Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
                <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
                <div id="feltar-option">
                  <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                  <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                  <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                  <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                  <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
                </div>

                <br>
                  <b id="descrb" >
                    This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                  </b>
                <br>
                  <div id="catogr">
                    <span id="type-catogr">Analytics and creative thinking</span>
                    <span id="type-catogr">Garden Design</span>
                    <span id="type-catogr">render</span>
                  </div>
              </div>
            </div>

      </div>

      <div class="more">
        <button type="submit" id="mor" href="#"><span>See More  </span><img src="{{asset('res/images/Arrow - Right.svg')}}" height="12px" width="13px"></button>
      </div>
      <br>
    </main>
    <footer class="footer">
      <div class="side1">
        <img class="fLogo" src="{{asset('res/images/Logo.svg')}}" alt="Logo">
        <p>All rights reserved <sup>©</sup></p>
        <a href=""><img src="{{asset('res/images/Social Media - Small - Dark - Insta.svg')}}" height="18px" width="18px"></a>
        <a href=""><img src="{{asset('res/images/Social Media - Small - Dark - Twitter.svg')}}" height="18px" width="18px"></a>
        <a href=""><img src="{{asset('res/images/Social Media - Small - Dark - Facebook.svg')}}" height="18px" width="18px"></a>
      </div>
      <div class="center">
        <p>Sky</p>
        <a href="">About Sky</a> <br><br>
        <a href=""> Services Sky</a><br><br>
        <a href="">new registration</a><br><br>

      </div>
      <div class="side2">
        <a href="">About Sky</a> <br><br>
        <a href=""> Services Sky</a><br><br>
        <a href="">new registration</a><br><br>
        <a href="">new registration</a><br><br>
      </div>


    </footer>

    <!--js -->
    <script src="{{asset('res/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{asset('res/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('res/js/viwe-prof.js')}}"></script>
    <script src="{{asset('res/js/script.js')}}"></script>
  </body>
</html>
