<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--CSS -->
    <link href="{{asset('res/css/all.min.css')}}" rel="stylesheet" >
    <link href="{{asset('res/css/bootstrap.min.css')}}" rel="stylesheet" >
    <link href="{{asset('res/css/my Proposal.css')}}" rel="stylesheet" >
    <link rel="stylesheet" href="{{asset('res/css/viwe-prof.css')}}">
    <link rel="stylesheet" href="{{asset('res/css/5. my Proposal(View My A  Proposal).css')}}">

    <!-- favicon -->
    <link rel="shortcut icon" href="{{asset('res/images/Logo.svg')}}" type="image/x-icon" />

    <title>my Proposal</title>
  </head>
  <body>
    <header class="h">
      <div class="h1">
        <img class="Logo" src="{{asset('res/images/Logo.svg')}}" alt="Logo">
        <a id="h1-a" href="/Users/AL-FAJR/Desktop/Project/gal1/index.html">Gallery</a>
        <a id="main" href="">Find Work</a>
        <a id="h1-a" href="">Forum</a>
        <a id="h1-a" href="">Store</a>
      </div>


      <div class="h2">
        <a id="h2-a" href=""><img src="{{asset('res/images/mes.svg')}}" height="10px" width="auto"></a>
        <a id="h2-a" href=""><img src="{{asset('res/images/not.svg')}}" height="25px" width="auto"></a>
        <button class="content-button" onclick="viewbutton();"><a id="h2-a1"><img id="profile" src="{{asset('res/images/profile.png')}}" height="45px" width="45px"></a>
        </button>

        <div id="file-div" class="contents-items">
          <ul class="items-list">
              <li><a href="Profile – 1.html">Profile</a></li>
              <li>Account</li>
              <li>Setting</li>
              <li>Log Out</li>
      </div>

    </header>
    <main>
      <div id="navi">
        <a id="a" href="Homepage (Freelancing) .html">Search for jobs</a>
        <a id="select-nav" href="#">my Proposal</a>
        <a id="a" href="my jobs.html">my jobs</a>
        <a id="a" href="Reports (Empty).html">Reports</a>
        <a id="a" href="">Message</a>
      </div>
      <div id="jop-option" >
            <a id="jop-a" href="#">Accepted</a>
            <a id="jop-a1" href="myprop1.html">Pending</a>
            <a id="jop-a1" href="myprop2.html">Rejected</a>
      </div>

      <div id="componnt">
        <div id="jop">
            <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>

            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
              <button id="mypro" type="submit">View My A  Proposal</button>
          </div>
        <!-- View My A  Proposal -->
        <div id="myModal" class="modal">
          <div class="modal-content" id="modcont">
              <div id="c-budget" >
                  <h2>How do you want to be paid?</h2>
                  <span id="budget">Client's budget:  <label for="">$300.00</label>USD</span>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled" disabled checked>
                  <label class="form-check-label" for="flexCheckDisabled">
                      By project
                  </label> <br>
                  <span id="date-space">Get your entire payment at the end, when all work has been delivered.</span>
              </div>
              <h2>the full amount you'd like to bid for this job</h2>
            <div id="price" >
           <div id="cent"> <span>Bid</span><input id="price1" type="text" name="" id=""disabled input> </div>
           <div id="cent"><span><strong>Sky</strong> Service Fee</span><input id="price1" type="text" name="" id="" disabled input></div>
              <div id="cent"><span>You’ll Receive</span><input id="price1" type="text" name="" id="" disabled input></div>
              </div>

              <span id="long">How long will this project take? <label id="time" for="">1-3 Months</label></span>
              <span id="Cover">Cover Letter</span>
              <b id="b">This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
              <h2 id="attch">Attachment</h2>
              <a href="http://"><img src="{{asset('res/images/File name.svg')}}" alt="" height="12px" width="12px"><label id="file" for="">File Name</label></a>
              <a href="http://"><img src="{{asset('res/images/File name.svg')}}" alt="" height="12px" width="12px"><label id="file" for="">File Name</label></a>
              <a href="http://"><img src="{{asset('res/images/File name.svg')}}" alt="" height="12px" width="12px"><label id="file" for="">File Name</label></a>


          <div class="close">
              <svg height="329pt" viewBox="0 0 329.26933 329" width="329pt" xmlns="http://www.w3.org/2000/svg"><path d="m194.800781 164.769531 128.210938-128.214843c8.34375-8.339844 8.34375-21.824219 0-30.164063-8.339844-8.339844-21.824219-8.339844-30.164063 0l-128.214844 128.214844-128.210937-128.214844c-8.34375-8.339844-21.824219-8.339844-30.164063 0-8.34375 8.339844-8.34375 21.824219 0 30.164063l128.210938 128.214843-128.210938 128.214844c-8.34375 8.339844-8.34375 21.824219 0 30.164063 4.15625 4.160156 9.621094 6.25 15.082032 6.25 5.460937 0 10.921875-2.089844 15.082031-6.25l128.210937-128.214844 128.214844 128.214844c4.160156 4.160156 9.621094 6.25 15.082032 6.25 5.460937 0 10.921874-2.089844 15.082031-6.25 8.34375-8.339844 8.34375-21.824219 0-30.164063zm0 0"/></svg>
          </div>
      </div>

     </div>

     <div id="jop">
      <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
      <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
      <div id="feltar-option">
        <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
        <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
        <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
        <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
        <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
        <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
      </div>

      <br>
        <b id="descrb" >
          This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
        </b>
      <br>
        <div id="catogr">
          <span id="type-catogr">Analytics and creative thinking</span>
          <span id="type-catogr">Garden Design</span>
          <span id="type-catogr">render</span>
        </div>
        <button id="mypro" type="submit">View My A  Proposal</button>
    </div>
    <div id="jop">
      <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
      <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
      <div id="feltar-option">
        <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
        <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
        <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
        <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
        <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
        <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
      </div>

      <br>
        <b id="descrb" >
          This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
        </b>
      <br>
        <div id="catogr">
          <span id="type-catogr">Analytics and creative thinking</span>
          <span id="type-catogr">Garden Design</span>
          <span id="type-catogr">render</span>
        </div>
        <button id="mypro" type="submit">View My A  Proposal</button>
    </div>
    <div id="jop">
      <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
      <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
      <div id="feltar-option">
        <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
        <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
        <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
        <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
        <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
        <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
      </div>

      <br>
        <b id="descrb" >
          This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
        </b>
      <br>
        <div id="catogr">
          <span id="type-catogr">Analytics and creative thinking</span>
          <span id="type-catogr">Garden Design</span>
          <span id="type-catogr">render</span>
        </div>
        <button id="mypro" type="submit">View My A  Proposal</button>
    </div>

          <div id="jop">
            <a href="Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>

            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
              <button id="mypro" type="submit">View My A  Proposal</button>
          </div>
          <div id="jop">
            <a href="Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>

            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
              <button id="mypro" type="submit">View My A  Proposal</button>
          </div>

          <div id="jop">
            <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
            <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
            <div id="feltar-option">
              <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
              <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
              <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
              <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
              <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
            </div>

            <br>
              <b id="descrb" >
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
              </b>
            <br>
              <div id="catogr">
                <span id="type-catogr">Analytics and creative thinking</span>
                <span id="type-catogr">Garden Design</span>
                <span id="type-catogr">render</span>
              </div>
              <button id="mypro" type="submit">View My A  Proposal</button>
          </div>
          <div id="see-more">
            <div id="jop">
              <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
              <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
              <div id="feltar-option">
                <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
              </div>

              <br>
                <b id="descrb" >
                  This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                </b>
              <br>
                <div id="catogr">
                  <span id="type-catogr">Analytics and creative thinking</span>
                  <span id="type-catogr">Garden Design</span>
                  <span id="type-catogr">render</span>
                </div>
                <button id="mypro" type="submit">View My A  Proposal</button>
            </div>
            <div id="jop">
              <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
              <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
              <div id="feltar-option">
                <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
              </div>

              <br>
                <b id="descrb" >
                  This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                </b>
              <br>
                <div id="catogr">
                  <span id="type-catogr">Analytics and creative thinking</span>
                  <span id="type-catogr">Garden Design</span>
                  <span id="type-catogr">render</span>
                </div>
                <button id="mypro" type="submit">View My A  Proposal</button>
            </div>
            <div id="jop">
              <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
              <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
              <div id="feltar-option">
                <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
              </div>

              <br>
                <b id="descrb" >
                  This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                </b>
              <br>
                <div id="catogr">
                  <span id="type-catogr">Analytics and creative thinking</span>
                  <span id="type-catogr">Garden Design</span>
                  <span id="type-catogr">render</span>
                </div>
                <button id="mypro" type="submit">View My A  Proposal</button>
            </div>
            <div id="jop">
              <a href="My Proposal Details Job.html" ><span id="addres">An architect is required to do urban planning for a garden</span></a>
              <br> <img src="{{asset('res/images/Time.svg')}}" alt="" height="12px" width="auto"> <label id="date-space">5 minutes ago</label> <br>
              <div id="feltar-option">
                <div id="cent"><img src="{{asset('res/images/Fixed-Price.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Job Type</label>  </div>
                <div id="cent"><img src="{{asset('res/images/Experience level.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Intermediate </label>   </div>
                <div id="cent"><img src="{{asset('res/images/Budget.svg')}}" alt="" height="14px" width="auto"> <span id="date-feltar">Budget: <label for="">$300</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Proposals.svg')}}" alt="" height="12px" width="auto"> <span id="date-feltar">Proposals: <label for=""> 5 to 10</label></span> </div>
                <div id="cent"><img src="{{asset('res/images/Payment verified.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">Payment unverified</label></div>
                <div id="cent"><img src="{{asset('res/images/Location.svg')}}" alt="" height="12px" width="auto"> <label id="date-feltar">USA</label></div>
              </div>

              <br>
                <b id="descrb" >
                  This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. This text is an example of a text that can be replaced In the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application
                </b>
              <br>
                <div id="catogr">
                  <span id="type-catogr">Analytics and creative thinking</span>
                  <span id="type-catogr">Garden Design</span>
                  <span id="type-catogr">render</span>
                </div>
                <button id="mypro" type="submit">View My A  Proposal</button>
            </div>
            </div>

      </div>

      <div class="more">
        <button type="submit" id="mor" href="#"><span>See More  </span><img src="{{asset('res/images/Arrow - Right.svg')}}" height="12px" width="13px"></button>
      </div>
      <br>
    </main>
    <footer class="footer">
      <div class="side1">
        <img class="fLogo" src="{{asset('res/images/Logo.svg')}}" alt="Logo">
        <p>All rights reserved <sup>©</sup></p>
        <a href=""><img src="{{asset('res/images/Social Media - Small - Dark - Insta.svg')}}" height="18px" width="18px"></a>
        <a href=""><img src="{{asset('res/images/Social Media - Small - Dark - Twitter.svg')}}" height="18px" width="18px"></a>
        <a href=""><img src="{{asset('res/images/Social Media - Small - Dark - Facebook.svg')}}" height="18px" width="18px"></a>
      </div>
      <div class="center">
        <p>Sky</p>
        <a href="">About Sky</a> <br><br>
        <a href=""> Services Sky</a><br><br>
        <a href="">new registration</a><br><br>

      </div>
      <div class="side2">
        <a href="">About Sky</a> <br><br>
        <a href=""> Services Sky</a><br><br>
        <a href="">new registration</a><br><br>
        <a href="">new registration</a><br><br>
      </div>


    </footer>

    <!--js -->
    <script src="{{asset('res/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{asset('res/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('res/js/script.js')}}"></script>
    <script src="{{asset('res/js/viwe-prof.js')}}"></script>
    <script src="{{asset('res/js/my Proposal(View My A  Proposal).js')}}"></script>

  </body>
</html>
